export interface WebAppUser {
    stravaAthleteId: number,
    id: string,
    userName: string,
    normalizedUserName: string,
    email: string,
    emailConfirmed: boolean,
    passwordHash: string,
    securityStamp: string,
    concurrencyStamp: string,
    phoneNumber?: number,
    phoneNumberConfirmed?: string,
    twoFactorEnabled: boolean,
    lockoutEnd: boolean,
    lockoutEnabled: boolean,
    accessFaileDcount: number,
}

//   "stravaAthleteId": 381648,
//     "id": "0150cce6-046b-41c6-820b-8dc9f92efd02",
//     "userName": "tyler.stambaugh@icloud.com",
//     "normalizedUserName": "TYLER.STAMBAUGH@ICLOUD.COM",
//     "email": "tyler.stambaugh@icloud.com",
//     "normalizedEmail": "TYLER.STAMBAUGH@ICLOUD.COM",
//     "emailConfirmed": true,
//     "passwordHash": "AQAAAAEAACcQAAAAEIE/msfSiV8oSgvc9+PTsR7tWz3S1JfVv9ptLzkmNJFDf/SbE6+ojVDHowjbWLnaQg==",
//     "securityStamp": "AUPXA4LJ3SWVES25C23MY5FHTXZUOYVD",
//     "concurrencyStamp": "9515e75a-86ad-4570-a254-86b3a75d2d21",
//     "phoneNumber": null,
//     "phoneNumberConfirmed": false,
//     "twoFactorEnabled": false,
//     "lockoutEnd": null,
//     "lockoutEnabled": true,
//     "accessFailedCount": 0